<?php

namespace Flower\StockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getTotalCount()
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('COUNT(p)');
        $qb->where('p.enabled = :enabled')->setParameter('enabled', true);

        return $qb->getQuery()->getSingleScalarResult();
    }

    public function getTotalCountWithouhStock()
    {
        $qb = $this->createQueryBuilder('p');

        $qb->select('COUNT(p)');
        $qb->where('p.stock <= 0');

        return $qb->getQuery()->getSingleScalarResult();
    }
}
