<?php

namespace Flower\StockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * StockChangeLogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockChangeLogRepository extends EntityRepository
{
}
